import fs from 'fs';
import path from 'path';

function readSource(relativePath: string): string {
  return fs.readFileSync(path.resolve(process.cwd(), relativePath), 'utf8');
}

describe('payment, calendar, and export artifact branding contracts', () => {
  it('keeps external payment, calendar, race-file, and results export artifacts BetterAt-branded', () => {
    const resultsExport = readSource('services/results/ResultsExportService.ts');
    const createPaymentIntent = readSource('supabase/functions/create-payment-intent/index.ts');
    const stripeCreatePayout = readSource('supabase/functions/stripe-create-payout/index.ts');
    const calendarService = readSource('services/CalendarService.ts');
    const nativePaymentService = readSource('services/PaymentService.native.ts');
    const onRegistrationCreated = readSource('supabase/functions/on-registration-created/index.ts');
    const blwGenerator = readSource('services/sailwave/BLWGenerator.ts');
    const trackingService = readSource('services/tracking/TrackingService.ts');

    expect(resultsExport).toContain('Generated by BetterAt • RRS Appendix A Low Point Scoring System');
    expect(resultsExport).not.toContain('Generated by RegattaFlow • RRS Appendix A Low Point Scoring System');

    expect(createPaymentIntent).toContain("let paymentDescription = description || 'BetterAt Payment';");
    expect(createPaymentIntent).not.toContain("'RegattaFlow Payment'");

    expect(stripeCreatePayout).toContain("description: 'BetterAt coach earnings payout'");
    expect(stripeCreatePayout).not.toContain('RegattaFlow coach earnings payout');

    expect(calendarService).toContain('PRODID:-//BetterAt//Coaching Session//EN');
    expect(calendarService).toContain('UID:${Date.now()}@better.at');
    expect(calendarService).toContain('Managed by BetterAt Coach Marketplace');
    expect(calendarService).toContain('Managed by BetterAt');
    expect(calendarService).not.toContain('PRODID:-//RegattaFlow//Coaching Session//EN');
    expect(calendarService).not.toContain('@regattaflow.com');
    expect(calendarService).not.toContain('Managed by RegattaFlow');

    expect(nativePaymentService).toContain("merchantDisplayName: 'BetterAt Coach Marketplace'");
    expect(nativePaymentService).not.toContain("merchantDisplayName: 'RegattaFlow Coach Marketplace'");

    expect(onRegistrationCreated).toContain("Deno.env.get('APP_URL') || 'https://better.at'");
    expect(onRegistrationCreated).toContain('Powered by <a href="https://better.at">BetterAt</a>');
    expect(onRegistrationCreated).toContain('Powered by BetterAt');
    expect(onRegistrationCreated).not.toContain('https://app.regattaflow.com');
    expect(onRegistrationCreated).not.toContain('Powered by <a href="https://regattaflow.com">RegattaFlow</a>');
    expect(onRegistrationCreated).not.toContain('Powered by RegattaFlow');

    expect(blwGenerator).toContain('Sailwave BLW file generated by BetterAt');
    expect(blwGenerator).toContain('https://better.at');
    expect(blwGenerator).not.toContain('Sailwave BLW file generated by RegattaFlow');
    expect(blwGenerator).not.toContain('https://regattaflow.com');

    expect(trackingService).toContain('creator="BetterAt"');
    expect(trackingService).toContain("'BetterAt Track'");
    expect(trackingService).not.toContain('creator="RegattaFlow"');
    expect(trackingService).not.toContain("'RegattaFlow Track'");
  });
});
